# Generated by Django 4.2.2 on 2025-05-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teknopark_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='entrepreneur_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='investor_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
