# Generated by Django 4.2.2 on 2025-05-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teknopark_app', '0002_match_entrepreneur_accepted_match_investor_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='entrepreneur_accepted',
        ),
        migrations.RemoveField(
            model_name='match',
            name='investor_accepted',
        ),
    ]
