# Generated by Django 4.2.2 on 2025-05-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teknopark_app', '0004_matchproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=10),
        ),
    ]
