# Generated by Django 4.2.2 on 2025-05-21 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teknopark_app', '0006_match_entrepreneur_accepted_match_investor_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('investor', models.ForeignKey(blank=True, limit_choices_to={'role': 'investor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meeting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='teknopark_app.meetingday')),
            ],
        ),
    ]
