# Generated by Django 4.2.2 on 2025-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teknopark_app', '0008_customuser_talep_edilen_yatirim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ths',
            field=models.CharField(blank=True, choices=[('1', 'THS-1 seviyesi'), ('2', 'THS-2 seviyesi'), ('3', 'THS-3 seviyesi'), ('4', 'THS-4 seviyesi'), ('5', 'THS-5 seviyesi'), ('6', 'THS-6 seviyesi'), ('7', 'THS-7 seviyesi'), ('8', 'THS-8 seviyesi'), ('9', 'THS-9 seviyesi')], max_length=2, null=True),
        ),
    ]
